# Generated by Django 3.1.7 on 2021-03-08 22:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_tweet_author'),
        ('twitteruser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='followers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='tweets',
            field=models.ManyToManyField(blank=True, to='tweet.Tweet'),
        ),
    ]
