# Generated by Django 3.1.7 on 2021-03-09 01:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0002_auto_20210308_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='dependencies',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
